### ISSUE TITLE
Performace issue

### ISSUE THREAD

**Issue by frnjjq** [magonzalezc/PSNRtool#2]
Buenos días,

Estoy usando el modulo estos días y me he dado cuenta de que es muy lento. He visto que la conversion a yuv está hecha manualmente cuando pillow te la hace automaticamente(mas rapido ya que es en c).

Dime si sigues viendo esto y te hago un Pr con el arreglo

**Comment by magonzalezc** [comment]
Hola!

Muchas gracias por tu comentario!  Lo cierto es que hice PSNRtool para
aprender un poco más de conversiones yuv entre otras cosillas de imagen y
por eso no está optimizado.  Si tienes el arreglo, hazme el pr por favor y
lo adjunto. Intentaré revisar el código yo también porque ya eres la
segunda persona que me escribe sobre PSNRtool. La verdad es que no pensé
que alguien lo encontraría útil y no me detuve mucho a pensar sobre
necesidades de otros.

Un saludo y gracias!!

**Comment by frnjjq** [comment]
Si, es muy util para calcular el PSNR ahi rapidito, yo la he usado mucho :D. 

Si te apetece revisar el codigo tambien he visto que la imagen se carga en memoria varias veces que no es necesario. Pero vamos con este cambio de que el Yuv te lo haga el pillow la velocidad ya se queda muy decente.

Esta claro que aun que en un pricipio fuera para ti, los que la usamos pues ayudamos un poquito 👯‍♂️ 

Cuidate!
